import $ from 'jquery'
import '@fortawesome/fontawesome-free/css/all.css'
import 'bootstrap'
import 'bootstrap/dist/css/bootstrap.css'

import '../css/admin-layout.scss'
import './/destroy-btn.js'
import './flatpickr.js'
import './calendar.js'
import './dropzone.js'
import './article.js'
import './ckeditor.js'